blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/ktanaha/tatedoc-editor/discussions
    about: For questions that are neither bugs nor feature requests
